# Generated by Django 3.0.8 on 2020-07-24 11:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangoapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KegiatanSarpras',
            fields=[
                ('kodeKegiatan', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('namaKegiatan', models.CharField(max_length=200)),
                ('keterangan', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Kegiatan',
                'verbose_name_plural': 'Kegiatan',
            },
        ),
        migrations.CreateModel(
            name='ProgramSarpras',
            fields=[
                ('kodeProgram', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('namaProgram', models.CharField(max_length=200)),
                ('keterangan', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Program',
            },
        ),
        migrations.CreateModel(
            name='Sarpras',
            fields=[
                ('kodeSarpras', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('namaSarpras', models.CharField(max_length=150)),
                ('tahun', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='static/uploads/%Y/%m/%d')),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('keterangan', models.TextField(max_length=300)),
                ('kodeKegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp1.KegiatanSarpras')),
            ],
            options={
                'verbose_name_plural': 'Kegiatan Sarana',
            },
        ),
        migrations.AddField(
            model_name='kegiatansarpras',
            name='kodeProgram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp1.ProgramSarpras'),
        ),
    ]
