# Generated by Django 3.0.8 on 2020-07-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0002_auto_20200724_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsarpras',
            name='kodeProgram',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
