# Generated by Django 3.0.8 on 2020-08-02 01:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0004_auto_20200724_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='kecamatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeKec', models.CharField(max_length=10)),
                ('namaKec', models.CharField(max_length=50)),
                ('namaKec2', models.CharField(max_length=45)),
                ('keterangan', models.TextField(max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Daftar Kecamatan',
            },
        ),
        migrations.AlterModelOptions(
            name='programsarpras',
            options={'permissions': (('read_item', 'can read_item'),), 'verbose_name': 'Program', 'verbose_name_plural': 'Program'},
        ),
    ]
