# Generated by Django 3.0.8 on 2020-08-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0005_auto_20200802_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kecamatan',
            name='keterangan',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
