# Generated by Django 3.0.8 on 2020-08-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0007_auto_20200802_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='JalanPropinsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeJalanP', models.IntegerField()),
                ('namaJalanP', models.CharField(max_length=70)),
                ('fungsiJalanP', models.CharField(max_length=40)),
                ('panjangJalanP', models.FloatField()),
                ('lebarJalanP', models.FloatField()),
                ('photo', models.ImageField(null=True, upload_to='static/uploads/%Y/%m/%d')),
                ('kondisiJalanP', models.CharField(max_length=15)),
                ('keterangan', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '5. Jalan Propinsi',
                'ordering': ('kodeJalanP',),
            },
        ),
        migrations.AlterModelOptions(
            name='kecamatan',
            options={'ordering': ('kodeKec',), 'verbose_name_plural': '1. Daftar Kecamatan'},
        ),
        migrations.AlterModelOptions(
            name='kegiatansarpras',
            options={'ordering': ('kodeKegiatan',), 'verbose_name': 'Kegiatan', 'verbose_name_plural': '3. Kegiatan'},
        ),
        migrations.AlterModelOptions(
            name='programsarpras',
            options={'ordering': ('kodeProgram',), 'permissions': (('read_item', 'can read_item'),), 'verbose_name': 'Program', 'verbose_name_plural': '2. Program'},
        ),
        migrations.AlterModelOptions(
            name='sarpras',
            options={'ordering': ('kodeSarpras',), 'verbose_name_plural': '4. Kegiatan Sarana'},
        ),
    ]
