# Generated by Django 3.0.8 on 2020-08-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0008_auto_20200805_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jalanpropinsi',
            name='kodeJalanP',
            field=models.CharField(max_length=10),
        ),
    ]
