# Generated by Django 3.0.8 on 2020-08-05 08:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0009_auto_20200805_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='jalanpropinsi',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326),
        ),
    ]
