# Generated by Django 3.0.8 on 2020-08-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0010_jalanpropinsi_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jalanpropinsi',
            name='keterangan',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jalanpropinsi',
            name='kodeJalanP',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jalanpropinsi',
            name='kondisiJalanP',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='jalanpropinsi',
            name='lebarJalanP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='jalanpropinsi',
            name='panjangJalanP',
            field=models.FloatField(null=True),
        ),
    ]
