# Generated by Django 3.0.8 on 2020-08-05 09:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0012_auto_20200805_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='JalanKabupaten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeJalanK', models.CharField(max_length=10, null=True)),
                ('namaJalanK', models.CharField(max_length=70)),
                ('fungsiJalanK', models.CharField(max_length=40, null=True)),
                ('panjangJalanK', models.FloatField(null=True)),
                ('lebarJalanK', models.FloatField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='static/uploads/%Y/%m/%d')),
                ('kondisiJalanK', models.CharField(max_length=15, null=True)),
                ('keterangan', models.TextField(max_length=100, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': '6. Jalan Kabupaten',
                'ordering': ('kodeJalanK',),
            },
        ),
    ]
