# Generated by Django 3.0.8 on 2020-08-05 10:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0014_auto_20200805_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastrukturjalan',
            name='lokasi',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
    ]
