# Generated by Django 3.0.8 on 2020-08-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0015_auto_20200805_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarpras',
            name='userS',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
