# Generated by Django 3.0.8 on 2020-08-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0016_sarpras_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarpras',
            name='verifikasiS',
            field=models.BooleanField(default=False),
        ),
    ]
