# Generated by Django 3.0.8 on 2020-08-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0017_sarpras_verifikasis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarpras',
            name='verifikasiS',
            field=models.BooleanField(default=True),
        ),
    ]
