# Generated by Django 2.2 on 2021-03-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0019_dinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinas',
            name='kodeKegiatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp1.KegiatanSarpras'),
        ),
    ]
