# Generated by Django 2.2 on 2021-03-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0023_auto_20210323_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinas',
            name='posisi',
        ),
        migrations.RemoveField(
            model_name='dinas',
            name='tahunInput',
        ),
        migrations.AddField(
            model_name='dinas',
            name='anggaran2016',
            field=models.FloatField(default=0.0),
        ),
    ]
