"""
Django settings for django1 project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

if os.name == 'nt':
    import platform
    OSGEO4W = r"C:\OSGeo4W"
    if '64' in platform.architecture()[0]:
        OSGEO4W += "64"
    assert os.path.isdir(OSGEO4W), "Directory does not exist: " + OSGEO4W
    #os.environ['OSGEO4W_ROOT'] = OSGEO4W
    #os.environ['GDAL_DATA'] = OSGEO4W + r"\share\gdal"
    #os.environ['PROJ_LIB'] = OSGEO4W + r"\share\proj"
    #os.environ['PATH'] = OSGEO4W + r"\bin;" + os.environ['PATH']
    GDAL_LIBRARY_PATH = 'C:/OSGeo4W64/bin/gdal204.dll'
    GEOS_LIBRARY_PATH = r'C:/OSGeo4W64/bin/geos_c.dll'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g8k=bua04=(ezqnlwt&7^h@x-3wi3_k*(t@qro4184prw9y*l('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'leaflet',
    'crispy_forms',
    'djangoapp1.apps.Djangoapp1Config',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'db_okuselatan2020_1',
        'HOST': 'database-1.cag2d2oxfxfn.us-east-2.rds.amazonaws.com',
        'USER': 'postgres',
        'PASSWORD':'xert2101',
        'PORT':'5431',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'okuselatan2020@gmail.com'
#EMAIL_HOST_PASSWORD = 'Danau_Ranau'
EMAIL_HOST_PASSWORD = 'dbthstzftdoxgjww' #password dari google security app

LEAFLET_CONFIG = {
    #'SPATIAL_EXTENT': (5.0, 44.0, 7.5, 46)
    'DEFAULT_CENTER': (-4.7, 103.89),
    'DEFAULT_ZOOM': 10,
    'MAX_ZOOM': 20,
    'MIN_ZOOM':3,
    'DEFAULT_PRECISION': 6,
    'SCALE': 'both',
    'MINIMAP': True,
    'RESET_VIEW': False,
    'NO_GLOBALS' : False,
    'FORCE_IMAGE_PATH': True,
    #'TILES': [('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'),],
    'TILES': 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    'ATTRIBUTION_PREFIX': 'Django for WebGIS - WawanHN',
}

# leaflet Module
LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (-4.529974, 104.100456), #default center of your map
    'DEFAULT_ZOOM': 14, # default zoom level
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 20,
    'SCALE': 'both',
    'ATTRIBUTION_PRIFIX': 'tekson', #attribution of your map
    'RESET_VIEW': False,
        'TILES': [('OpenStreetMap', 'http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
          'attribution': '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
        }),
        ('Drak Map', 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', {
            'attribution': '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            'subdomains': 'abcd',
            'maxZoom': 19
        })],
    }

#GEOS_LIBRARY_PATH = 'E:\Python\pyawsec2\venv\Lib\site-packages\osgeo\geos_c.dll'
#GDAL_LIBRARY_PATH = 'E:/Python/pyawsec2/venv/Lib/site-packages/osgeo/gdal301.dll'
#GDAL_LIBRARY_PATH = 'G:/OSGeo4W64/bin/gdal204.dll'
#GEOS_LIBRARY_PATH = r'G:/OSGeo4W64/bin/geos_c.dll'
